#ifndef CONFIG_H
#define CONFIG_H

#define WIN_W 900
#define WIN_H 900

#define TARGET_FPS 60
#define TARGET_FRAMETIME (1.0 / TARGET_FPS)

#define RECT_W 170
#define RECT_H 20
#define BORDER_RADIUS 10

#define RAND_VALUE 7

#define PLAYER_MOVE_DURATION 0.15
#define PAUSE_MOVE_DURATION 0.15
#define LB_ANIM_PHASE1_DURATION 0.20f
#define LB_ANIM_PHASE2_DURATION 0.30f
#define LB_ANIM_LINE_THICKNESS 6.0f

#define IDLE_HOLD_TIME 1.0
#define IDLE_FRAME_TIME 0.15


#endif
